### ISSUE TITLE
.vtx files not allowed by gmad whitelist

### ISSUE THREAD

**Issue by MinimeTheGreat** [Facepunch/gmad#49] opened 2024-06-14 23:08 UTC
.vtx files prevent .gma compilation even when in models folder/subfolders
Is there a reason for this? They were previously supported.
If they can be added to the whitelist that would be greatly appreciated.
![whitelist](https://github.com/Facepunch/gmad/assets/35642236/c714d824-7896-4241-89ff-097b90ec88cb)

**Comment by robotboy655** [comment] 2024-06-14 23:14
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5903

**Closed by robotboy655** 2024-06-14 23:14 UTC
